#
# (C) Copyriht 2012 Henrik Nordstrom <henrik@henriknordstrom.net>
#
# Based on some other board Makefile
#
# (C) Copyright 2000-2003
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# See file CREDITS for list of people who contributed to this
# project.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307 USA
#

obj-y	+= board.o
obj-$(CONFIG_A13_OLINUXINO)	+= dram_a13_olinuxino.o
obj-$(CONFIG_A13_MID)		+= dram_a13_mid.o
obj-$(CONFIG_A7HD)		+= dram_hyundai_a7hd.o
obj-$(CONFIG_CUBIEBOARD)	+= dram_cubieboard.o
obj-$(CONFIG_CUBIEBOARD_512)	+= dram_cubieboard_512.o
obj-$(CONFIG_HACKBERRY)		+= dram_hackberry.o
obj-$(CONFIG_MELE_A1000)	+= dram_mele_a1000.o
obj-$(CONFIG_MELE_A3700)	+= dram_mele_a3700.o
obj-$(CONFIG_MINI_X)		+= dram_mini_x.o
obj-$(CONFIG_MK802)		+= dram_mk802.o
obj-$(CONFIG_MK802II)		+= dram_mk802ii.o
